CREATE TABLE STUDENTS (
STUDENT_ID SERIAL PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
EMAIL VARCHAR(100),
ENROLLMENT_DATE DATE
);

CREATE TABLE ASSIGNMENTS (
ASSIGNMENT_ID SERIAL PRIMARY KEY,
TITLE VARCHAR(100),
DESCRIPTION TEXT,
DUE_DATE DATE,
STUDENT_ID INT REFERENCES STUDENTS(STUDENT_ID)
);

INSERT INTO STUDENTS (FIRST_NAME, LAST_NAME, EMAIL, ENROLLMENT_DATE)
VALUES ('Kaniqua', 'Outlaw', 'kloutlaw@my.waketech.edu', '2025-01-08');

INSERT INTO ASSIGNMENTS (TITLE, DESCRIPTION, DUE_DATE, STUDENT_ID)
VALUES ('LAB7 POSTGRES', 
'SET UP A DATABASE AND INSERT RECORDS AS DESCRIBED IN THE INSTRUCTIONS.', 
'2025-02-28', 
2281553);


